create type account_role as enum ( 'moderator', 'admin' );

create domain first_name as text constraint first_name_not_empty check ( trim(value) <> '');
create domain last_name as text constraint last_name_not_empty check ( trim(value) <> '');
create domain nickname as text constraint nickname_not_empty check ( trim(value) <> '');

create domain date_of_birth as date constraint valid_date_of_birth check (
    value <= current_date - interval '13 years' and
    value >= current_date - interval '120 years' );

create domain stripe_customer_id as text;

create table account (
    account_id         int generated by default as identity primary key,
    stripe_customer_id stripe_customer_id unique,
    roles              account_role[]     not null default array []::account_role[],
    email              email              not null unique,
    nickname           nickname unique,
    first_name         first_name         not null,
    last_name          last_name          not null,
    full_name          text generated always as ( first_name || ' ' || last_name ) stored,
    display_name       text               not null generated always as ( coalesce(
            nickname,
            first_name || ' ' ||
            left(last_name, 1) ||
            '.')) stored,
    dob                date_of_birth,
    avatar_url         url,
    bio                text
        constraint bio_length check (length(bio) <= 500),

    country_code       country_code       not null,
    currency_code      currency_code      not null generated always as (
        case country_code
            when 'us' then 'usd'::currency_code
            when 'ca' then 'cad'::currency_code
            when 'gb' then 'gbp'::currency_code
        end
        ) stored,

    measurement_system measurement_system not null generated always as (
        case country_code
            when 'us' then 'imperial'::measurement_system
            else 'metric'::measurement_system
        end
        ) stored,

    last_login_ip      inet               not null,
    last_login_at      timestamptz        not null,

    created_at         timestamptz        not null default now(),
    updated_at         timestamptz        not null default now(),
    deleted_at         timestamptz
);

create table account_contact (
    account_contact_id  int generated by default as identity primary key,
    account_id          int         not null references account,
    contact             contact     not null,
    is_default_shipping bool        not null default false,

    created_at          timestamptz not null default now(),
    updated_at          timestamptz
);

comment on table account_contact is $$
    A contact (i.e name and address) associated with an account.
    This table should never be referenced via foreign keys, as its rows can be modified, which is undesirable
    when e.g. storing the delivery address for a shipment. For this reason, the `contact` field should be copied into
    whatever entity needs it (e.g. a purchase).

    Only one contact per account can be set as the default for shipping.
$$;

create unique index one_default_shipping_per_account
    on account_contact (account_id)
    where is_default_shipping = true;

comment on column account.display_name is $$
    The public-facing name of the user. Will be their nickname if they have one, else their first name and last initial.
$$;

create table internal_login (
    email         email primary key,
    password_hash text        not null check (trim(password_hash) <> ''),
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),

    constraint fk_internal_login_email foreign key (email) references account (email) on update cascade on delete cascade
);

comment on table internal_login is $$
Holds login credentials for users who have completed email/password signup.
There can only be one internal login per user.
$$;

create type external_provider as enum ('google', 'apple');

create table external_login (
    account_id     int               not null references account (account_id) on delete cascade,
    provider_id    external_provider not null,
    provider_token text              not null unique check (trim(provider_token) <> ''),
    created_at     timestamptz       not null default now(),

    constraint unique_account_provider unique (account_id, provider_id)
);

comment on table external_login is $$
A user can have multiple external logins (e.g. Google, Apple).
These can exist in parallel with an internal login.
$$;

comment on constraint unique_account_provider on external_login is $$
A user cannot have multiple logins with the same provider.
$$;

create table pending_registration (
    email                  email primary key,
    first_name             first_name,
    last_name              last_name,
    password_hash          text         not null,
    verification_code_hash text         not null,
    country_code           country_code not null,
    created_at             timestamptz  not null default now()
);

comment on table pending_registration is $$
Holds users who have not yet completed signup. Once they verify their email,
they are moved to the account table and their row is deleted from here.
$$;

create table password_reset (
    password_reset_id int generated by default as identity primary key,
    email             email references internal_login (email) on delete cascade on update restrict,
    reset_code_hash   text        not null unique,
    expires_at        timestamptz not null default now() + interval '10 minutes',
    requested_at      timestamptz not null default now(),
    requested_by_ip   inet        not null,
    approved_at       timestamptz,
    approved_by_ip    inet
);

create table auth_session (
    id          text primary key not null,
    data        bytea            not null,
    expiry_date timestamptz      not null
);

create table login_event (
    login_event_id bigint generated by default as identity primary key,
    email          email references account (email) not null,
    ip_address     inet                             not null,
    user_agent     text,
    success        bool                             not null,
    created_at     timestamptz                      not null default now()
);

create index idx_external_login_account_id on external_login (account_id);