create domain shippo_account_id as text;
create domain stripe_account_id as text;


create type seller_type as enum (
    'individual',
    'company'
    );

create type carrier_code as enum (
    'usps',
    'fedex',
    'canada_post',
    'hermes_uk'
    );

create table pending_seller_registration (
    account_id        int references account primary key,
    stripe_account_id stripe_account_id unique not null,
    address           address                  not null,
    phone             phone                    not null unique,
    seller_type       seller_type              not null,
    carrier_codes     carrier_code[]           not null default array []::carrier_code[],
    company_name      text,

    created_at        timestamptz              not null default now()
);

comment on table pending_seller_registration is $$
    Represents an incomplete seller account, i.e. one that hasn't finished onboarding via Stripe.

    Upon insertion of a `seller` with the same `account_id`, the corresponding `pending_seller_registration`
    is automatically deleted via a trigger.

    This table is periodically scanned; any entries >1 month old are deleted along with their stripe accounts.
$$;


create table seller (
    account_id              int references account primary key,

    seller_type             seller_type              not null,

    shippo_account_id       shippo_account_id unique not null,
    stripe_account_id       stripe_account_id unique not null,

    stripe_charges_enabled  bool                     not null default false,
    stripe_payouts_enabled  bool                     not null default false,

    marketplace_fee_flat    int                      not null default 30,
    marketplace_fee_pct     numeric(5, 4)            not null default 0.095,

    company_name            text unique
        constraint company_name_not_empty check (trim(company_name) <> ''),
    address                 address                  not null,
    phone                   phone unique             not null,

    free_shipping_threshold currency,

    away_until              timestamptz              not null default '1970-01-01 00:00:00+00'::timestamptz,

    created_at              timestamptz              not null default now(),
    updated_at              timestamptz              not null default now()
);


comment on column seller.away_until is $$
    Sellers can pause their account so users cannot buy from them.
    This is useful when they go on vacation.
$$;

comment on column seller.marketplace_fee_flat is $$
    Flat fee taken by Miniswap on all sales from this seller in US cents.
    Note: this never has to be currency-converted, because Stripe handles collection for us.
$$;

comment on column seller.marketplace_fee_pct is $$
    Percentage fee taken by Miniswap on all sales from this seller.
$$;

create index idx_seller_account_id on seller (account_id);

-- IMPORTANT: Keep dimension and weight constraints consistent with listing and parcel tables
create table parcel_template (
    parcel_template_id int generated by default as identity primary key,
    account_id         int            not null references account,
    name               text           not null
        constraint name_not_empty check (trim(name) <> ''),

    -- User input dimensions (for display and storage)
    length             numeric(10, 2) not null
        constraint length_gt_zero check (length > 0),
    width              numeric(10, 2) not null
        constraint width_gt_zero check (width > 0),
    height             numeric(10, 2) not null
        constraint height_gt_zero check (height > 0),
    dimensions_unit    distance_unit  not null,

    -- Weight constraints for packing
    weight             numeric(10, 2) not null default 0
        constraint weight_gte_zero check (weight >= 0),
    weight_limit       numeric(10, 2)
        constraint weight_limit_gt_zero check (weight_limit is null or weight_limit > 0),
    weight_unit        mass_unit,
    weight_limit_unit  mass_unit,

    -- Ensure weight_limit_unit is provided when weight_limit is specified
    constraint weight_limit_unit_consistency check (
        weight_limit is null or weight_limit_unit is not null
        ),
    
    -- Ensure weight_unit is provided when weight > 0
    constraint weight_unit_consistency check (
        weight = 0 or weight_unit is not null
        ),


    -- Unit-aware weight constraints (max 20 lbs) when specified
    constraint weight_max check (
        weight = 0 or (
            (weight_unit = 'g' and weight <= 9071.85) or
            (weight_unit = 'kg' and weight <= 9.07185) or
            (weight_unit = 'oz' and weight <= 320) or
            (weight_unit = 'lb' and weight <= 20)
            )
        ),

    -- Unit-aware constraints for dimensions (max 50 inches)
    constraint template_length_max check (
        (dimensions_unit = 'in' and length <= 50) or
        (dimensions_unit = 'ft' and length <= 4.17) or
        (dimensions_unit = 'cm' and length <= 127) or
        (dimensions_unit = 'mm' and length <= 1270) or
        (dimensions_unit = 'm' and length <= 1.27)
        ),
    constraint template_width_max check (
        (dimensions_unit = 'in' and width <= 50) or
        (dimensions_unit = 'ft' and width <= 4.17) or
        (dimensions_unit = 'cm' and width <= 127) or
        (dimensions_unit = 'mm' and width <= 1270) or
        (dimensions_unit = 'm' and width <= 1.27)
        ),
    constraint template_height_max check (
        (dimensions_unit = 'in' and height <= 50) or
        (dimensions_unit = 'ft' and height <= 4.17) or
        (dimensions_unit = 'cm' and height <= 127) or
        (dimensions_unit = 'mm' and height <= 1270) or
        (dimensions_unit = 'm' and height <= 1.27)
        ),

    created_at         timestamptz    not null default now(),
    deleted_at         timestamptz
);

comment on column parcel_template.dimensions_unit is 'The unit that was used when creating the parcel template';

create unique index parcel_template_account_id_name_unique_not_deleted
    on parcel_template (account_id, name)
    where deleted_at is null;

-- Ensure a user cannot have duplicate parcel templates with the same dimensions
create unique index parcel_template_account_dimensions_unique_not_deleted
    on parcel_template (account_id, length, width, height, dimensions_unit)
    where deleted_at is null;

create table carrier (
    carrier_code carrier_code not null primary key,
    carrier_name text         not null
);

comment on table carrier is 'A shipping carrier, e.g. FedEx or USPS. Carrier codes come from Shippo, e.g.
  fedex, usps. https://docs.goshippo.com/shippoapi/public-api/#tag/Carriers';

create table seller_carrier (
    seller_id         int          not null references seller,
    carrier_code      carrier_code not null references carrier,
    shippo_carrier_id text         not null,
    is_enabled        bool         not null default true,

    created_at        timestamptz  not null default now(),
    updated_at        timestamptz  not null default now(),

    -- seller cannot have multiple of same carrier
    primary key (seller_id, carrier_code)
);

comment on table seller_carrier is $$
    Each seller has their own Shippo carrier accounts.
$$;

comment on column seller_carrier.shippo_carrier_id is 'Shippo-generated carrier ID for the seller shippo account';

create table seller_suspension (
    seller_suspension_id int generated by default as identity primary key,
    account_id           int         not null references seller,
    moderator_id         int         not null references account (account_id),
    reason               text        not null,
    until                timestamptz not null default 'infinity',
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);