create type category_kind as enum (
    'manufacturer',
    'game',
    'faction',
    'paint_range'
    );

create type category_segment as
(
    display_name text,
    url_path     text
);

create table category (
    category_id  int generated by default as identity primary key,
    path         ltree  not null unique,
    kind         category_kind,
    name         text   not null
        constraint category_name_not_empty check (trim(name) <> ''),
    display_path text[] not null default array []::text[]
);

create index category_name_search_idx on category using gin (to_tsvector('english', name));

-- Performance index for category path lookups
create index idx_category_path on category (path);
comment on index idx_category_path is $$
    Speeds up category lookups by path in api.get_product and related queries.
    The path column already has a unique constraint, but this non-unique index
    can be more efficient for lookups that don't need uniqueness checking.
$$;


comment on column category.display_path is
    'Computed out of the name fields and paths of each category in a given category path via a trigger.';