create type product_type as enum (
    'miniature',
    'paint'
    );

create type mini_material as enum ('paper', 'plastic', 'metal', 'resin');
create type mini_packaging as enum ('box', 'blister', 'loose');

create type paint_type as enum ('regular', 'contrast', 'air', 'wash', 'primer', 'oil', 'enamel', 'varnish');

create type paint_packaging as enum ('can', 'pot', 'dropper');

create type mini_sculpt_type as enum ('digital', 'hand');

create domain scale_mm as int constraint scale_gt_zero check (value > 0);

create table product (
    product_id       int generated by default as identity primary key,
    product_type     product_type     not null,
    name             text             not null
        constraint product_name_not_empty check (trim(name) <> ''),
    slug             slug             not null,
    sku              text             not null,
    release_date     date,
    description      text,
    official_url     url unique,
    msrp             currency
        constraint msrp_amount_gt_zero check ((msrp).amount > 0),
    length           numeric(10, 2),
    width            numeric(10, 2),
    height           numeric(10, 2),
    dimensions_unit  distance_unit,
    weight           numeric(10, 2),
    weight_unit      mass_unit,
    is_discontinued  bool, -- Oftentimes unknown

    -- Mini
    mini_scale_mm    scale_mm,
    mini_material    mini_material
        constraint mini_material_not_null check ((product_type = 'miniature') =
                                                 (mini_material is not null)),
    mini_packaging   mini_packaging
        constraint mini_packaging_not_null check ((product_type = 'miniature') =
                                                  (mini_packaging is not null)),
    mini_model_count int
        constraint mini_model_count_not_null check ((product_type = 'miniature') =
                                                    (mini_model_count is not null))
        constraint mini_model_count_gt_zero check (mini_model_count > 0),
    mini_sculpt_type mini_sculpt_type not null default 'digital',

    -- Paint
    paint_type       paint_type
        constraint paint_type_not_null check ((product_type = 'paint') = (paint_type is not null)),
    paint_packaging  paint_packaging
        constraint paint_packaging_not_null check ((product_type = 'paint') =
                                                   (paint_packaging is not null)),
    paint_ml         int
        constraint paint_ml_not_null check ((product_type = 'paint') = (paint_ml is not null))
        constraint paint_ml_gt_zero check (paint_ml > 0),

    created_at       timestamptz      not null default now(),
    updated_at       timestamptz      not null default now(),

    constraint unique_product_name_sku unique (name, sku)
);


create table product_category (
    product_category_id int generated by default as identity primary key,
    product_id          int references product  not null,
    category_id         int references category not null,
    is_primary          bool                    not null default false,

    created_at          timestamptz             not null default now()
);

create unique index one_primary_category_per_product
    on product_category (product_id)
    where is_primary = true;

comment on table product is $$
    Denormalized representation of all products users call sell on Miniswap.
$$;

comment on column product.slug is 'Unique slug auto-generated from the product name if not provided.';

create index product_name_search_idx on product using gin (to_tsvector('english', name));

-- Performance index for product slug lookups (used in api.get_product)
create index idx_product_slug on product (slug);
comment on index idx_product_slug is $$
    Speeds up product lookups by slug in api.get_product and similar queries.
    Critical for product page performance.
$$;

create index idx_product_category_product_id on product_category (product_id);
create index idx_product_category_category_id on product_category (category_id);

-- Composite index for efficient category-based product lookups
create index idx_product_category_composite on product_category (category_id, product_id) 
    where is_primary = true;
comment on index idx_product_category_composite is $$
    Optimizes queries that fetch products for a specific category.
    Filtered to primary categories only since that's what api.get_product uses.
$$;

create table watch_product (
    product_id int references product not null,
    account_id int references account not null,

    created_at timestamptz            not null default now(),

    primary key (product_id, account_id)
);