create type return_shipping_type as enum ('no_returns', 'buyer_pays', 'seller_pays');
create type assembly_status as enum ( 'new_in_box', 'on_sprue', 'partially_assembled', 'fully_assembled' );
create type painting_status as enum ( 'unpainted', 'stripped', 'primed', 'partially_painted', 'tabletop_standard', 'professional_standard' );
create type content_status as enum ('complete', 'incomplete', 'bits', 'kitbash');

create table item (
    item_id              int generated by default as identity primary key,
    account_id           int         not null references account,
    product_id           int         not null references product on delete restrict,
    description          text
        constraint description_not_empty check (trim(description) <> ''),

    mini_assembly_status assembly_status,
    mini_painting_status painting_status
        constraint unassembled_minis_cannot_be_painted
            check (not (mini_assembly_status in ('new_in_box', 'on_sprue')) or
                   (mini_painting_status = 'unpainted')),

    mini_content_status  content_status
        constraint new_minis_must_be_complete check
            (mini_assembly_status != 'new_in_box' or mini_content_status = 'complete'),

    mini_color           hex_color
        constraint mini_color_not_null_for_fully_painted check (
            mini_painting_status not in ('professional_standard', 'tabletop_standard')
                or mini_color is not null),

    -- Paint
    paint_is_opened      bool,

    archived_at          timestamptz,

    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

comment on column item.archived_at is $$
    Time the item was archived. Archived items don't appear in the category/product listings.
$$;

-- IMPORTANT: Keep dimension and weight constraints consistent with parcel and parcel_template tables
create table listing (
    item_id               int references item primary key,

    initial_quantity      int            not null default 1
        constraint initial_quantity_available_gt_zero check (initial_quantity > 0)
        constraint initial_quantity_available_lt_1000 check (initial_quantity < 1000),

    price                 currency       not null
        constraint price_gt_min check ((price).amount >= 500)
        constraint price_lt_max check ((price).amount < 100000),

    length                numeric(10, 2) not null
        constraint length_gt_zero check (length > 0),
    width                 numeric(10, 2) not null
        constraint width_gt_zero check (width > 0),
    height                numeric(10, 2) not null
        constraint height_gt_zero check (height > 0),
    dimensions_unit       distance_unit  not null,
    weight                numeric(10, 2) not null
        constraint weight_gt_zero check (weight > 0),
    weight_unit           mass_unit      not null,

    -- Unit-aware constraints for dimensions (max 50 inches)
    constraint length_max check (
        (dimensions_unit = 'in' and length <= 50) or
        (dimensions_unit = 'ft' and length <= 4.17) or
        (dimensions_unit = 'cm' and length <= 127) or
        (dimensions_unit = 'mm' and length <= 1270) or
        (dimensions_unit = 'm' and length <= 1.27)
        ),
    constraint width_max check (
        (dimensions_unit = 'in' and width <= 50) or
        (dimensions_unit = 'ft' and width <= 4.17) or
        (dimensions_unit = 'cm' and width <= 127) or
        (dimensions_unit = 'mm' and width <= 1270) or
        (dimensions_unit = 'm' and width <= 1.27)
        ),
    constraint height_max check (
        (dimensions_unit = 'in' and height <= 50) or
        (dimensions_unit = 'ft' and height <= 4.17) or
        (dimensions_unit = 'cm' and height <= 127) or
        (dimensions_unit = 'mm' and height <= 1270) or
        (dimensions_unit = 'm' and height <= 1.27)
        ),

    -- Unit-aware constraint for weight (max 20 lbs)
    constraint weight_max check (
        (weight_unit = 'g' and weight <= 9071.85) or
        (weight_unit = 'kg' and weight <= 9.07185) or
        (weight_unit = 'oz' and weight <= 320) or
        (weight_unit = 'lb' and weight <= 20)
        ),

    -- Optional reference to the parcel template used for dimensions
    parcel_template_id    int references parcel_template (parcel_template_id),

    is_enabled            bool           not null default true,
    seller_pays_shipping  bool           not null default false,
    pack_individually     bool           not null default false,
    is_shipped_externally bool           not null default false,
    returns_accepted      bool           not null default true,

    created_at            timestamptz    not null default now(),
    updated_at            timestamptz    not null default now()
);

comment on table listing is $$
    All information related to selling an item.
$$;

comment on column listing.length is 'Length in the unit specified by dimensions_unit';
comment on column listing.width is 'Width in the unit specified by dimensions_unit';
comment on column listing.height is 'Height in the unit specified by dimensions_unit';
comment on column listing.dimensions_unit is 'Unit of measurement for length, width, and height';
comment on column listing.weight is 'Weight in the unit specified by weight_unit';
comment on column listing.weight_unit is 'Unit of measurement for weight';
comment on column listing.price is 'Price of the item in the currency of the seller.';
comment on column listing.seller_pays_shipping is 'Whether or not the seller is paying for shipping of the listing.';
comment on column listing.is_shipped_externally is 'If true, this listing is to be shipped without using a Miniswap Shippo-generated label.';

create index idx_listing_item_id on listing (item_id);

-- Performance indexes for account page queries
create index idx_item_account_id on item (account_id) where archived_at is null;
comment on index idx_item_account_id is $$
    Speeds up queries that fetch all items for a specific account.
    Filtered to exclude archived items since they're not shown in listings.
$$;

create index idx_item_account_created on item (account_id, created_at desc);
comment on index idx_item_account_created is $$
    Composite index to speed up account item queries that sort by created_at.
    Enables index-only scans for the common pattern of fetching items by account ordered by date.
$$;

-- Performance index for product-based item lookups
create index idx_item_product_id on item (product_id) where archived_at is null;
comment on index idx_item_product_id is $$
    Critical for api.get_product and similar queries that fetch items for a specific product.
    Filtered to exclude archived items to keep index smaller and more efficient.
$$;

-- Note: Status is computed in core.listing, not stored in the table

create table inventory_adjustment (
    inventory_adjustment_id int generated by default as identity primary key,
    item_id                 int references listing not null,
    delta                   int                    not null,

    created_at              timestamptz            not null default now()
);

comment on table inventory_adjustment is $$
    A change in an listing's stock. This can be from:
    1. the seller restocking/correcting the quantity
    2. syncing with the seller's shopify store
$$;

create index idx_inventory_adjustment_item_id on inventory_adjustment (item_id);

create table list (
    list_id    int primary key generated by default as identity,
    account_id int         not null references account,
    name       text        not null
        constraint name_not_empty check (trim(name) <> ''),

    created_at timestamptz not null default now()
);

create table list_product (
    list_id    int         not null references list,
    product_id int         not null references product,

    created_at timestamptz not null default now()
);