create table wishlist (
    wishlist_id int generated by default as identity primary key,
    account_id  int         not null references account,
    item_id     int         not null references item,
    
    created_at  timestamptz not null default now(),
    
    constraint unique_account_item unique (account_id, item_id)
);

comment on table wishlist is $$
    Items saved by users to their wishlist for later viewing/purchasing.
    Each user can only have one wishlist entry per item.
$$;

comment on constraint unique_account_item on wishlist is $$
    Prevents duplicate wishlist entries for the same item by the same user.
$$;

-- Performance index for item-based wishlist lookups
create index idx_wishlist_item_account on wishlist(item_id, account_id);
comment on index idx_wishlist_item_account is $$
    Speeds up wishlist status checks when joining from items to wishlist.
    Complements the unique constraint index (account_id, item_id) which is optimized for the opposite direction.
$$;