create table product_image (
    product_image_id int generated by default as identity primary key,
    product_id       int references product not null,
    path             text                   not null
        constraint path_not_empty check (trim(path) <> ''),
    display_order    int                    not null default 0,

    is_copyrighted   bool                   not null default false,
    is_transparent   bool                   not null default false,

    created_at       timestamptz            not null default now(),

    unique (product_id, display_order)
);

create index product_image_product_id_idx on product_image (product_id);

create table item_image (
    item_image_id int generated by default as identity primary key,
    item_id       int references item not null,
    path          text                not null
        constraint path_not_empty check (trim(path) <> ''),
    display_order int                 not null default 0,

    created_at    timestamptz         not null default now(),
    deleted_at    timestamptz
);

create unique index item_image_item_id_display_order_unique_not_deleted on item_image (item_id, display_order) where deleted_at is null;

create index item_image_item_id_idx on item_image (item_id);

comment on table product_image is $$
    Images associated with products.
$$;

comment on table item_image is $$
    Images associated with items.
$$;